;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;Copyright (c) 2013 Manolis Agkopian		    ;
;See the file LICENCE for copying permission.	    ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	;
	;LED BLINK WITH TIMER 1, WITH 524288uS DELAY (ABOUT 0.5S)
	;
	
	PROCESSOR '16F876A'
	INCLUDE <P16F876A.INC>

	__CONFIG _XT_OSC & _WDT_OFF & _PWRTE_OFF & _CP_OFF & _LVP_OFF & _BODEN_OFF
	
	ORG 0x0000
	GOTO INIT
	ORG 0x0004
	GOTO TMR1_INT
	
INIT:
	BSF INTCON, PEIE ;ENABLE PERITHERIAL INTERUPTS
	
	BSF STATUS, RP0 ;SELECT BANK 01
	BCF TRISB, 0
	BSF PIE1, TMR1IE ;ENABLE TIMER 1 INTERUPT
	BCF STATUS, RP0 ;SELECT BANK 00
	
	MOVLW B'00110001' ;TIMER 1 WILL COUNT ONCE EVERY 8 CYCLES, THE OSCILLATOR IS DIABLED
	MOVWF T1CON ;AND IT USES THE INTERNAL CLOCK (FOSC/4) (FOR 4MHZ CLOCK, T = 0.25uS => 0.25uS * 4 PULSES = 1 CYCLE IN 1uS => 1uS * 2^16 * 8 = 524288uS = ABOUT 0.5S)
	;(2^16 BECAUSE TIMER 1 IS 16BITS)
	
	
	CLRF TMR1L ;CLEAR TIMER 1 LOW BYTE
	CLRF TMR1H ;CLEAR TIMER 1 LOW HIGH
	BCF PORTB, 0
	
	BCF PIR1, TMR1IF ;CLEAR TIMER 1 OVERFLOW FLAG
	BSF INTCON, GIE

MAIN:
	GOTO $

TMR1_INT:
	BCF INTCON, GIE ;DISABLE ALL INTERUPTS
	BCF PIR1, TMR1IF ;CLEAR TIMER 1 OVERFLOW FLAG
	
	BTFSC PORTB, 0 ;IF PB0 IS SET
	GOTO CLR_PB0 ;THEN CLEAR IT
	
	BSF PORTB, 0 ;ELSE IF IS CLEAR, THEN SET IT
	GOTO CONTINUE
	
CLR_PB0:
	BCF PORTB, 0
	
CONTINUE:
	
	BSF INTCON, GIE ;RENABLE THE INTERUPTS
	RETFIE
	END