;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;Copyright (c) 2013 Manolis Agkopian		    ;
;See the file LICENCE for copying permission.	    ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	PROCESSOR '16F72A'
	INCLUDE <P16F72.inc>

	__CONFIG _XT_OSC & _WDT_OFF & _PWRTE_OFF & _CP_OFF & _BODEN_OFF

LED EQU 0

	CBLOCK 0x20
CNT0
CNT1
CNT2
	ENDC

	ORG 0x00
INIT:
	BSF STATUS, RP0 ;SELECT BANK 01
	BCF TRISB, LED ;PB0 IS AN OUTPUT
	BCF STATUS, RP0 ;SELECT BANK 00
	BCF PORTB, LED
MAIN:
	BSF PORTB, LED ;SET PB0 HIGH
	CALL DELAY
	BCF PORTB, LED ;SET PB1 LOW
	CALL DELAY
	GOTO MAIN

DELAY:
	MOVLW 0xA0
	MOVWF CNT2
D2:
	MOVLW 0xFA
	MOVWF CNT1
D1:
	MOVLW 0xFA
	MOVWF CNT0
D0:
	DECFSZ CNT0
	GOTO D0

	DECFSZ CNT1
	GOTO D1

	DECFSZ CNT2
	GOTO D2

	RETURN

	END
